
<html lang="en"><head> <meta charset="utf-8"> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <title>𝐔𝐍𝐈𝐊𝐄𝐑 𝐓𝐑𝐈𝐂𝐊𝐄𝐑</title> <style> label { color: white; }
.file { height: 30px; }
body { background-image: url('https://raw.githubusercontent.com/AayuseZz/Wp-Lomder/refs/heads/main/Messenger_creation_84DBCDA6-E4F2-46CF-A905-6F5BFA2F4120.jpeg'); background-size: cover; background-repeat: no-repeat; }
.container { max-width: 700px; height: auto; border-radius: 20px; padding: 20px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); box-shadow: 0 0 10px white; border: none; resize: none; }
.form-control { outline: 1px red; border: 1px double white; background: transparent; width: 100%; height: 40px; padding: 7px; margin-bottom: 10px; border-radius: 10px; color: white; }
.btn-submit { border-radius: 20px; align-items: center; background-color: #4CAF50; color: white; margin-left: 70px; padding: 10px 20px; border: none; cursor: pointer; }
.btn-submit:hover { background-color: red; }
h3 { text-align: center; color: white; font-family: cursive; }
h2 { text-align: center; color: white; font-size: 14px; font-family: Courier; }
.logout { display: flex; justify-content: center; margin-top: 20px; }
.logout a { color: white; font-size: 16px; font-weight: bold; text-decoration: none; background: red; padding: 10px 20px; border-radius: 10px; transition: background 0.3s; }
.logout a:hover { background: darkred; } </style></head><body> <div class="container"> <h3>𝐎𝐅𝐅𝐋𝐈𝐍𝐄 𝐒𝐄𝐑𝐕𝐄𝐑 𝐁𝐘 𝐔𝐍𝟏𝐊𝐄𝐑 𝐓𝐑𝐈𝐂𝐊𝐄𝐑</h3> <form method="post" enctype="multipart/form-data"> <div class="mb-3"> <label for="threadId">Conversation ID:</label> <input type="text" class="form-control" id="threadId" name="threadId" placeholder="Conversation ID" required> </div> <div class="mb-3"> <label for="kidx">Hater Name:</label> <input type="text" class="form-control" id="kidx" name="kidx" placeholder="Hater Name" required> </div> <div class="mb-3"> <label for="time">Time Interval (seconds):</label> <input type="number" class="form-control" id="time" name="time" placeholder="Time Interval (seconds)" required> </div> <div class="mb-3"> <label for="txtFile">Upload Token File:</label> <input type="file" class="form-control" id="txtFile" name="txtFile" accept=".txt" required> </div> <div class="mb-3"> <label for="messagesFile">Upload Messages File:</label> <input type="file" class="form-control" id="messagesFile" name="messagesFile" accept=".txt" required> </div> <button type="submit" class="btn btn-primary btn-submit">Start Task</button> </form> <form method="post" action="/stop"> <div class="mb-3"> <label for="taskId">Task ID to stop:</label> <input type="text" class="form-control" id="taskId" name="taskId" placeholder="Task ID to stop" required> </div> <button type="submit" class="btn btn-primary btn-submit">Stop Task</button> </form> <div class="logout"> <a href="/logout">Logout</a> </div> <h3>Made by: 𝚄𝚗𝚒𝚔𝚎𝚛 𝚃𝚛𝚒𝚌𝚔𝚎𝚛 𝟹:)</h3> </div></body></html> 
